services:
  redis:
    image: redis:7-alpine
    container_name: cloud_store_redis
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxmemory",
        "64mb",
        "--maxmemory-policy",
        "allkeys-lru"
      ]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cloud_store_mailhog
    profiles: ["dev-tools"]
    ports:
      - "1025:1025"
      - "8025:8025"
