user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # 用户前台
    server {
        listen       8080;
        server_name  localhost;
        root   /usr/share/nginx/html/frontend;
        index  index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # 避免浏览器缓存 html 文件导致更新后无法加载新 JS
        location ~* \.html$ {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }
    }

    # 管理员后台
    server {
        listen       8083;
        server_name  localhost;
        root   /usr/share/nginx/html/admin;
        index  index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.html$ {
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }
    }
}
