ALTER TABLE nat_plans ADD COLUMN cpu_cores INT NOT NULL DEFAULT 1;
ALTER TABLE nat_plans ADD COLUMN bandwidth_mbps INT NOT NULL DEFAULT 100;
ALTER TABLE nat_plans ADD COLUMN traffic_gb INT NOT NULL DEFAULT 1000;